// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgfwsKfaAGmyoNpF9Y_2D6SbqyL13jgg8',
    appId: '1:288187774511:web:757881a91f1ae6f18878da',
    messagingSenderId: '288187774511',
    projectId: 'c2-33798',
    authDomain: 'c2-33798.firebaseapp.com',
    storageBucket: 'c2-33798.firebasestorage.app',
    measurementId: 'G-YWHZWY3181',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVt6E_Yp8Q_-VJ0144cUz_dBAUedaJNNg',
    appId: '1:288187774511:android:a8a47012121362e68878da',
    messagingSenderId: '288187774511',
    projectId: 'c2-33798',
    storageBucket: 'c2-33798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCph3PZ_-x3CEHpvC8J4pAcPK8R9qzXOFY',
    appId: '1:288187774511:ios:4de0a8fd80833d688878da',
    messagingSenderId: '288187774511',
    projectId: 'c2-33798',
    storageBucket: 'c2-33798.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
